name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Import kernel source
      uses: actions/checkout@v4  
      
    - name: "Set up build environment"
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core flex bison build-essential zip curl \
        zlib1g-dev libc6-dev-i386 lib32z1-dev unzip  

    - name: Setting permission
      run: |    
        chmod +x build.sh  

    - name: Cooking Kernel
      run: ./build.sh

    - name : Upload Output file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.device }}_Kernel_OUTPUT_File
        path: |
          out/*
